packages:
  - src/frontend
  - src/backend
  - src/shared

ignoredBuiltDependencies:
  - faiss-node
  - protobufjs
  - sharp

onlyBuiltDependencies:
  - '@nestjs/core'
  - bcrypt
  - core-js
  - esbuild
  - tesseract.js
